databases:
  - name: gradeup_db
    databaseName: gradeup_db
    user: gradeup_user
    plan: free

services:
  - type: web
    name: gradeup-app
    runtime: python
    branch: main
    plan: free
    buildCommand: "./build.sh"
    startCommand: ".venv/bin/gunicorn app:app"
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: gradeup_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11 