"""Initial migration

Revision ID: 6f816938dbb7
Revises: 2242e772ee6e
Create Date: 2025-05-24 12:13:35.774988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f816938dbb7'
down_revision = '2242e772ee6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('phone')
        batch_op.drop_column('location')
        batch_op.drop_column('bio')
        batch_op.drop_column('date_of_birth')
        batch_op.drop_column('preferences')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferences', sa.VARCHAR(collation='Cyrillic_General_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('bio', sa.VARCHAR(collation='Cyrillic_General_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=100, collation='Cyrillic_General_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=20, collation='Cyrillic_General_CI_AS'), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
