"""add password reset fields to user model

Revision ID: c929e7ae03fa
Revises: 9aa168edaa13
Create Date: 2025-06-10 10:13:12.026296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c929e7ae03fa'
down_revision = '9aa168edaa13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_reset_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('password_reset_token_expires', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_reset_token_expires')
        batch_op.drop_column('password_reset_token')

    # ### end Alembic commands ###
