"""add data collection tables

Revision ID: ea17f3ca9e66
Revises: 1641364135bc
Create Date: 2025-05-30 00:55:31.460427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea17f3ca9e66'
down_revision = '1641364135bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_export_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('export_type', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('exported_by', sa.Integer(), nullable=True),
    sa.Column('export_filters', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['exported_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=True),
    sa.Column('raw_data', sa.Text(), nullable=False),
    sa.Column('processed_data', sa.Text(), nullable=True),
    sa.Column('survey_metadata', sa.Text(), nullable=True),
    sa.Column('submission_ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('submission_time', sa.DateTime(), nullable=True),
    sa.Column('processing_status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['response_id'], ['survey_responses.id'], ),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('survey_data')
    op.drop_table('data_export_logs')
    # ### end Alembic commands ###
